name: Chore Workflow
on: [push, pull_request]

jobs:
  run-lint:
    strategy:
      matrix:
        version: ['1.16', '1.17', '1.18', '1.19']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: {{ matrix.version }}
      - uses: golangci/golangci-lint-action@v3
      - run: |
          golangci-lint run ./...
  run-tests:
    strategy:
      matrix:
        version: ['1.16', '1.17', '1.18', '1.19']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: {{ matrix.version }}
      - run: |
          go test ./...
